CREATE DATABASE saipos_todo CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE saipos_todo_test CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE users (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(200),
  email VARCHAR(200)
) ENGINE=INNODB;

CREATE TABLE todos (
  id VARCHAR(50) PRIMARY KEY,
  description VARCHAR(200),
  completed BOOLEAN DEFAULT FALSE,
  user_id VARCHAR(50),
  FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE history (
  id VARCHAR(50) PRIMARY KEY,
  date_time timestamp DEFAULT CURRENT_TIMESTAMP,
  type varchar(20),
  todo_id VARCHAR(50),
  FOREIGN KEY (todo_id) REFERENCES todos (id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;
